language: android

sudo: false

before_cache:
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

notifications:
  email: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"
    - AVD_DEBUG='init,avd_config,nand_limits,keys,adb,adbserver,adbclient'

matrix:
  include:
    - env: AVD_TARGET=android-15 ARGS='-PdisablePreDex'
#    - env: AVD_TARGET=android-16 ARGS='-PdisablePreDex'
    - env: AVD_TARGET=android-17 ARGS='-PdisablePreDex'
#    - env: AVD_TARGET=android-18 ARGS='-PdisablePreDex'
    - env: AVD_TARGET=android-19 ARGS='-PdisablePreDex'
#    - env: AVD_TARGET=android-21 ARGS='-PdisablePreDex'
    - env: AVD_TARGET=android-22 ARGS='-PdisablePreDex' TARGET_PKGS=android-22,sys-img-armeabi-v7a-android-22
    - env: AVD_TARGET=android-23 ARGS='-PdisablePreDex' TARGET_PKGS=sys-img-armeabi-v7a-android-23
#    - env: AVD_TARGET='Google Inc.:Google APIs:21' AVD_TAG=google_apis ARGS='-PdisablePreDex'
#           TARGET_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
#    - env: AVD_TARGET='Google Inc.:Google APIs:22' AVD_TAG=google_apis ARGS='-PdisablePreDex'
#           TARGET_PKGS=android-22,addon-google_apis-google-22,sys-img-armeabi-v7a-addon-google_apis-google-22
#    - env: AVD_TARGET='Google Inc.:Google APIs:23' AVD_TAG=google_apis ARGS='-PdisablePreDex'
#           TARGET_PKGS=addon-google_apis-google-23,sys-img-armeabi-v7a-addon-google_apis-google-23
  allow_failures:
#    - env: AVD_TARGET=android-21 ARGS='-PdisablePreDex'
    - env: AVD_TARGET=android-22 ARGS='-PdisablePreDex' TARGET_PKGS=android-22,sys-img-armeabi-v7a-android-22
    - env: AVD_TARGET=android-23 ARGS='-PdisablePreDex' TARGET_PKGS=sys-img-armeabi-v7a-android-23
#    - env: AVD_TARGET='Google Inc.:Google APIs:21' AVD_TAG=google_apis ARGS='-PdisablePreDex'
#           TARGET_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
#    - env: AVD_TARGET='Google Inc.:Google APIs:22' AVD_TAG=google_apis ARGS='-PdisablePreDex'
#           TARGET_PKGS=android-22,addon-google_apis-google-22,sys-img-armeabi-v7a-addon-google_apis-google-22
#    - env: AVD_TARGET='Google Inc.:Google APIs:23' AVD_TAG=google_apis ARGS='-PdisablePreDex'
#           TARGET_PKGS=addon-google_apis-google-23,sys-img-armeabi-v7a-addon-google_apis-google-23
  fast_finish: false

before_install:
  - if [[ "${ARGS:-}" == *-PdisablePreDex* ]]; then export PREDEX_OPT="-PdisablePreDex"; fi;

install:
  - ./execute install-and-update-sdk # Install and update the SDK based on env vars or Acib defaults
  - ./execute create-and-start-device # Create and start a device based on env vars or Acib defaults
  - ./execute wait-for-device-online # Start adbd, wait for device connected and show android serial
  - ./gradlew --version # Show version and download Gradle Wrapper when is not present in cache
  - ./gradlew clean # Clean project and download Android dependencies when are not present in cache
  - ./gradlew test ${PREDEX_OPT:-} # Run unit tests for all variants
  - ./execute show-debug-unit-test-results # Print debug unit test results on Travis-ci web
  - ./execute show-release-unit-test-results # Print release unit test results on Travis-ci web

before_script:
  - ./execute wait-for-device-ready # Wait until device is ready. Stopped state or custom sleep time

script:
  - travis_wait 15 ./gradlew cAT  ${PREDEX_OPT:-} # Install and runs android tests for all flavors
#  - travis_wait ./execute android-test

after_script:
  - ./execute show-android-test-results # Print intrumentation test results on Travis-ci web
